Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace inmobiliaria.Controllers
{
    public class PagosController : Controller
    {
        // GET: Pagos
        [Authorize]
        public ActionResult Index(int filtroContrato)
        {
            ViewBag.filtroContrato  = filtroContrato;
            
            ViewBag.Id = TempData["Id"];
            if(TempData.ContainsKey("Mensaje"))
            {
                ViewBag.Mensaje = TempData["Mensaje"];

            }
            var CR = new ContratosRepositorio();
            ViewBag.Contratos = CR.ObtenerTodos();
            var PR = new PagosRepositorio();
            //Logica de filtrado
            var todosP = PR.ObtenerTodos();
            List<Pagos> P = new List<Pagos>();
            List<bool> condiciones ;
            bool condicionFinal;
            for(int i = 0; i < todosP.Count ; i++){
                condicionFinal = true;
                condiciones = new List<bool>();
                if( filtroContrato != 0 ) condiciones.Add(filtroContrato == todosP[i].ContratoId.Id ); 
                for(int j = 0; j<condiciones.Count;j++) condicionFinal= condicionFinal && condiciones[j];

                if(condicionFinal) P.Add(todosP[i]);
            }
            return View(P);
        }

        // GET: Pagos/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
           
            var PR = new PagosRepositorio();
            var P = PR.ObtenerXId(id);
            return View(P);
        }

        // GET: Pagos/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.filtroContrato = TempData["filtroContrato"];
            ViewBag.Id = TempData["Id"];
            if(TempData.ContainsKey("Mensaje"))
            {
                ViewBag.Mensaje = TempData["Mensaje"];

            }
            var CR = new ContratosRepositorio();
            ViewBag.Contratos= CR.ObtenerTodos();

            var P = new Pagos();
            return View(P);
        }

        // POST: Pagos/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pagos p)
        {
            //Validaciones
             if (p.ContratoId.Id < 0)
            {
                TempData["Mensaje"]="Debes Elegir un Contrato";
                ModelState.AddModelError("ContratoId.Id", "Debes Elegir un Contrato");
                return RedirectToAction(nameof(Create));
            }
            if(p.Importe < 0){
                TempData["Mensaje"]="El campo Importe es obligatorio";
                ModelState.AddModelError("CA", "El campo Importe es obligatorio");
                return RedirectToAction(nameof(Create));
            }
            if(DateTime.Compare(p.Fecha,DateTime.MinValue)<0){
                TempData["Mensaje"]="El campo Fecha pes obligatorio";
                ModelState.AddModelError("Fecha", "El campo Fecha p es obligatorio");
                return RedirectToAction(nameof(Create));
            }
            //ViewBag
              TempData["filtroContrato"]= p.ContratoId.Id;
            try
            {
                var PR = new PagosRepositorio();
                var CR = new ContratosRepositorio();
                var id = PR.Alta(p);
                TempData["Id"] = id;
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                TempData["Mensaje"] = e.Message;
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Create));
            }
        }
        [Authorize]
        public ActionResult RenovarPago(int id){
            var CR = new ContratosRepositorio();
            try{
                var C = CR.ObtenerXId(id);
                TempData["filtroContrato"]= C.Id;
            }catch(Exception e){
                TempData["Mensaje"] = e.Message;
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Index));
            }
            
            return RedirectToAction(nameof(Create));
        }
        // GET: Pagos/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
             
            ViewBag.Id = TempData["Id"];
            if(TempData.ContainsKey("Mensaje"))
            {
                ViewBag.Mensaje = TempData["Mensaje"];

            }
            var CR = new ContratosRepositorio();

            ViewBag.Contratos= CR.ObtenerTodos();

            var PR = new PagosRepositorio();
            var P = PR.ObtenerXId(id);
            return View(P);
        }

        // POST: Pagos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, Pagos p)
        {
             //Validaciones
             if (p.ContratoId.Id < 0)
            {
                TempData["Mensaje"]="Debes Elegir un Contrato";
                ModelState.AddModelError("ContratoId.Id", "Debes Elegir un Contrato");
                return RedirectToAction(nameof(Create));
            }
            if(p.Importe < 0){
                TempData["Mensaje"]="El campo Importe es obligatorio";
                ModelState.AddModelError("CA", "El campo Importe es obligatorio");
                return RedirectToAction(nameof(Create));
            }
            if(DateTime.Compare(p.Fecha,DateTime.MinValue)<0){
                TempData["Mensaje"]="El campo Fecha pes obligatorio";
                ModelState.AddModelError("Fecha", "El campo Fecha p es obligatorio");
                return RedirectToAction(nameof(Create));
            }
            try
            {
                var PR = new PagosRepositorio();
                var bol =PR.Modificacion(id,p);
                if(bol)
                {
                  TempData["Mensaje"]="Se modifico con exito la entidad id:"+p.Id;
                return RedirectToAction(nameof(Index));  
                }else
                {
                    throw new Exception("No se pudo modificar con exito la entidad con id:"+p.Id);
                }
                
            }
            catch(Exception e)
            {
                TempData["Mensaje"] = e.Message;
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Edit));
            }
        }

        // GET: Pagos/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
             if (User.IsInRole("Empleado"))
                {
                        TempData["Mensaje"] = "No tienes permiso de realizar esta accion";
                        return RedirectToAction(nameof(Index), "Home"); 
            }
            ViewBag.Id = TempData["Id"];
            if(TempData.ContainsKey("Mensaje"))
            {
                ViewBag.Mensaje = TempData["Mensaje"];

            }
            var PR = new PagosRepositorio();
            var P = PR.ObtenerXId(id);  
            return View(P);
        }

        // POST: Pagos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Delete(int id, Pagos p)
        {
            if (User.IsInRole("Empleado"))
                {
                        TempData["Mensaje"] = "No tienes permiso de realizar esta accion";
                        return RedirectToAction(nameof(Index), "Home"); 
            }
            try
            {
                var PR = new PagosRepositorio();
                var CR = new ContratosRepositorio();
                p = PR.ObtenerXId(p.Id);
                var bol = PR.Baja(p);
                if(bol)
                {
                    TempData["Mensaje"] = "Se elimino con exito la entidad";
                    return RedirectToAction(nameof(Index));

                }else{
                    throw new Exception("No se logro eliminar la entidad id: "+id);
                }
            }
            catch(Exception e)
            {
                TempData["Mensaje"] = e.Message;
                Console.WriteLine(e.Message);
                return RedirectToAction(nameof(Delete));
            }
        }
        }
    }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/inmobiliaria.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">InmobiliariaGarro</a>
                <h4 class="navbar-brand" id="tituloPag"></h4>
                <div class="navbar-brand dropdown">
                    <button class="dropdown-toggle btn btn-outline-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Perfil
                    </button> 
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li><a class="dropdown-item nav-link" asp-area="" asp-controller="Usuarios" asp-action="Login"><i class="fa-solid fa-user-plus"></i> Login</a></li>
                        </ul>
                    }else
                    {
                        <ul class="dropdown-menu dropdown-menu-dark">
                            @if(User.IsInRole("Administrador")){
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="Administradores" asp-action="Perfil" asp-route-id=@User.Identity.Name><i class="fa-solid fa-user"></i> Ver Perfil</a></li>
                            }else{
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="Empleados" asp-action="Perfil" asp-route-id=@User.Identity.Name><i class="fa-solid fa-user"></i> Ver Perfil</a></li>
                            }
                                <li><a class="dropdown-item nav-link" asp-area="" asp-controller="Usuarios" asp-action="Logout" ><i class="fa-solid fa-right-from-bracket"></i> Salir</a></li>
                        </ul>
                    }
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title text-light" id="offcanvasDarkNavbarLabel">InmobiliariaGarro</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i> Inicio</a>
                            </li>
                            @if(User.Identity.IsAuthenticated )
                            {
                                @if(User.IsInRole("Administrador"))
                                {
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Index"> <i class="fa-solid fa-users"></i> Usuarios</a></li>  
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Administradores" asp-action="Index"><i class="fa-solid fa-handshake"></i> Administradores</a></li>  
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Empleados" asp-action="Index"><i class="fa-solid fa-folder"></i> Empleados</a></li>  
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="TiposEstados" asp-action="Index"><i class="fa-brands fa-typo3"></i> TiposEstados</a></li>  
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="TiposUsos" asp-action="Index"><i class="fa-brands fa-typo3"></i> TiposUsos</a></li>  
                                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="TiposInmuebles" asp-action="Index"><i class="fa-brands fa-typo3"></i> TiposInmuebles</a></li> 
                                }
                                
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Propietarios" asp-action="Index"><i class="fa-solid fa-address-book"></i> Propietarios</a></li>  
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Inquilinos" asp-action="Index"><i class="fa-regular fa-address-book"></i> Inquilinos</a></li>  
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Inmuebles" asp-action="Index"><i class="fa-solid fa-warehouse"></i> Inmuebles</a></li>
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Contratos" asp-action="Index"><i class="fa-solid fa-file-contract"></i> Contratos</a></li>  
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Pagos" asp-action="Index"><i class="fa-solid fa-money-bill-wave"></i> Pagos</a></li>                     
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div>
            @if(ViewBag.Id != null)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>!Exito¡</strong>La entidad fue dado de alta @ViewBag.Id
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            else if(ViewBag.Mensaje != null){
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    <strong>Informacion</strong> @ViewBag.Mensaje
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
        </div>
        <div class="container bg-blur" style="min-height: 70vh;" >@RenderBody()</div>
        
    </main>
    
    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <p class="text-light">&copy; 2023 - inmobiliaria - <a asp-area="" class="text-light" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>